### ISSUE TITLE
dynamic dispatch throws nSM instead of a type error

### ISSUE THREAD

**Issue by jmesserly** [dart-archive/dev_compiler#534]
This is affecting issue12284_test and inferrer_synthesized_constructor_test.

I discovered it by fixing dart:_runtime "callMethod" to correctly use the "symbol" instead of the "name" when looking up the method signature.

**Comment by jmesserly** [comment]
this affects dsend, dcall etc.

**Comment by jmesserly** [comment]
related: https://github.com/dart-lang/dev_compiler/issues/176

**Comment by munificent** [comment]
Appears to be doing the right thing now.

**Comment by vsmenon** [comment]
We haven't been tracking/updating issues left in `dart-archive/dev_compiler`.  All active ones should have been migrated to the sdk under `area-dev-compiler`.
